# FINAL docker-compose.yaml for development and easy file access

services:
  generator:
    build:
      context: ./wp31_services
      dockerfile: ./docker/energy-generator/Dockerfile
    ports: ["50051:50051"]
    volumes:
      # Link the local data folder directly to /data inside the container
      - ./wp31_services/data:/data
    restart: unless-stopped

  analyzer:
    build:
      context: ./wp31_services
      dockerfile: ./docker/energy-analyzer/Dockerfile
    ports: ["50052:50052"]
    volumes:
      # Link the SAME local data folder
      - ./wp31_services/data:/data
    restart: unless-stopped

  reporter:
    build:
      context: ./wp31_services
      dockerfile: ./docker/report-generator/Dockerfile
    ports: ["50053:50053"]
    volumes:
      # Link the SAME local data folder
      - ./wp31_services/data:/data
    restart: unless-stopped

# The top-level 'volumes:' key is no longer needed for this method