version: '3.8'
services:
  orchestrator:
    build:
      context: ..
      dockerfile: docker/orchestrator/Dockerfile
    volumes:
      - ../src/orchestrator:/app
      - ../config:/config
      - ../logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONFIG_DIR=/config
      - LOG_DIR=/logs
