version: '3.8'

services:
  orchestrator:
    build:
      context: ../
      dockerfile: docker/orchestrator/Dockerfile
    volumes:
      - ../src/orchestrator:/app
      - ../config:/config
      - ../logs:/logs
      - ../data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    environment:
      - CONFIG_DIR=/config
      - LOG_DIR=/logs
