# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: energy_pipeline.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'energy_pipeline.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x65nergy_pipeline.proto\"9\n\x0e\x45xecuteRequest\x12\x12\n\ninput_file\x18\x01 \x01(\t\x12\x13\n\x0boutput_file\x18\x02 \x01(\t\"3\n\x0f\x45xecuteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2A\n\x11\x43ontainerExecutor\x12,\n\x07\x45xecute\x12\x0f.ExecuteRequest\x1a\x10.ExecuteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'energy_pipeline_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXECUTEREQUEST']._serialized_start=25
  _globals['_EXECUTEREQUEST']._serialized_end=82
  _globals['_EXECUTERESPONSE']._serialized_start=84
  _globals['_EXECUTERESPONSE']._serialized_end=135
  _globals['_CONTAINEREXECUTOR']._serialized_start=137
  _globals['_CONTAINEREXECUTOR']._serialized_end=202
# @@protoc_insertion_point(module_scope)
